trigger:
- master

pool:
  name: slave-2

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: TomcatDeployment@1
  inputs:
        TomcatUrl: 'http://20.83.183.89:8080/'
        Username: 'tomcat'
        Password: 'admin@123'
        Warfile: 'target/myweb-8.7.2.war'
        Context: '/'
        ServerVersion: '7OrAbove'
    
  